services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Passionweb\DataHandler\:
    resource: "../Classes/*"

  Passionweb\DataHandler\Command\AddContentElement:
    tags:
      -   name: 'console.command'
          command: 'datahandler:contentelement'
          description: 'Add a content element to a page'
          schedulable: false